torchrun --nproc_per_node=4 -m main_finetune \
--ds_name iwatch \
--data_path "/niddk-data-central/SOL/PASOS/train/SOL_10hz" \
--remark CHAP-FT  \
--blr 1e-3 \
--model CHAP \
--epochs 10 \
--warmup_epochs 2 \
--batch_size 16 \
--weight_decay 1e-3 \
--subset_ratio 1.0 \
--pos_weight 1.0 \
--use_data_aug 1 