apiVersion: v1
kind: Pod
metadata:
  name: deep-postures
spec:
  containers:
  - name: deep-postures 
    image: ank028/deep-postures-pt
    imagePullPolicy: Always
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: "12Gi"
        cpu: 2
    volumeMounts:
      - name: fs-store
        mountPath: "/data"
  volumes:
  - name: fs-store
    flexVolume:
      driver: ceph.rook.io/rook
      fsType: ceph
      options:
        clusterNamespace: rook
        fsName: nautilusfs
        path: /niddk
        mountUser: niddk
        mountSecret: ceph-fs-secret
              
      
